### ISSUE TITLE
Dizajn

### ISSUE THREAD

**Issue by melonipinjusic** [dariomrk/EduLink#25]
- Izrada logoa projekta
Potpuna razrada (hi-fi) wireframe-a proizvoda
Minimalno 60% posto razrađenog UI-a
Funkcionalan prototip aplikacije (ako UI nije gotov, wireframe prototip je okej ili kombinacija wire i UI) - dakle ovo treba sadržavati više od onoga što će developeri napraviti, oni imaju bar 3 screena za implementaciju a prototip treba sadržavat više od toga
Materijali marketingu za oglase/objave

**Comment by dariomrk** [comment]
Non-dev issue @melonipinjusic
