### ISSUE TITLE
Marketing

### ISSUE THREAD

**Issue by melonipinjusic** [dariomrk/EduLink#26]
- [ ] Segmentacija - target audience i pain points skupine, postoji li slična aplikacija na tržištu i po čemu se vaša ističe
- [ ] Suradnja s dizajnom i devom za UI i UX - psihološke cake koje ta ciljana publika ima, Npr: takozvani digitalni domoroci drugačije scrollaju i koriste aplikacije naspram digitalnih migranata.
- [ ] Projekcija budžeta
- Marketinški plan:
- [ ] Vizualni identitet kampanje (s dizajnerima)
- [ ] Detaljan plan za organski marketing - od dizajnera tražite materijale za 2 objave
- [ ] Detaljan plan plaćenih oglasa - od dizajnera tražite materijale za 2 oglasa
- [ ] Search Engine Optimisation (SEO) i Search Engine Marketing (SEM) - suradnja s devovima, napisati kakve će oni korake poduzeti
- [ ] 1 SEO optimiziran blog post (uz plan kad bi se objavilo na webu)
- [ ] Tekstovi u aplikaciji
- [ ] Public Relations - mediji, Press Release i timeline kampanje
- [ ] Marketinške aktivnosti za budućnost

**Comment by dariomrk** [comment]
Non-dev tasks should not be converted to issues @melonipinjusic
